nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173'] # Autorisez votre front-end
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': ~
