# config/routes/attributes.yaml
controllers:
    resource:
        path: ../../src/Controller/OperationController.php
        namespace: App\Controller\
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute