version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:@db:3306/myBank?serverVersion=8.0.32&charset=utf8mb4"
      DATABASE_URL="mysql://root:@127.0.0.1:3306/myBank?serverVersion=8.0.32&charset=utf8mb4"

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: myBank
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
